"use client";

import type { AiSummaryResponse } from "@/lib/types";
import { Sparkles } from "lucide-react";

export function AiSummary({
  data,
  error,
}: {
  data: AiSummaryResponse | null;
  error: string | null;
}) {
  if (error) {
    return (
      <div className="card p-6 border-[#ef4444]/40">
        <div className="text-sm text-[#ef4444]">
          AI summary unavailable: {error}
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="card p-6">
        <div className="skeleton h-5 w-40 mb-3" />
        <div className="space-y-2">
          <div className="skeleton h-3 w-full" />
          <div className="skeleton h-3 w-11/12" />
          <div className="skeleton h-3 w-3/4" />
        </div>
      </div>
    );
  }

  return (
    <div className="card p-5 md:p-6 relative overflow-hidden">
      <div
        className="glow absolute"
        style={{
          top: -80,
          right: -80,
          width: 200,
          height: 200,
          background: "#8b5cf6",
          opacity: 0.12,
        }}
      />
      <div className="relative">
        <div className="flex items-center justify-between gap-3 mb-3">
          <div className="flex items-center gap-2">
            <div
              className="w-7 h-7 rounded-md flex items-center justify-center"
              style={{
                background: "rgba(139,92,246,0.15)",
                border: "1px solid rgba(139,92,246,0.4)",
              }}
            >
              <Sparkles size={14} style={{ color: "#a78bfa" }} />
            </div>
            <div>
              <div className="text-xs uppercase tracking-wider text-muted-foreground">
                Halo briefing
              </div>
              <div className="text-sm font-medium">
                {data.generated
                  ? `Generated by ${data.model}`
                  : "Computed from on-chain signals"}
              </div>
            </div>
          </div>
        </div>

        {data.headlines.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {data.headlines.map((h, i) => (
              <span
                key={i}
                className="text-xs px-2.5 py-1 rounded-md bg-muted/60 border border-border text-foreground/90"
              >
                {h}
              </span>
            ))}
          </div>
        )}

        <p className="text-sm text-foreground/90 leading-relaxed mb-3">
          {data.summary}
        </p>

        {data.recommendations.length > 0 && (
          <div className="mt-3 rounded-lg border border-border bg-muted/30 p-3">
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1.5">
              Recommended actions
            </div>
            <ul className="space-y-1 text-sm">
              {data.recommendations.map((r, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-muted-foreground shrink-0">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="text-foreground/90">{r}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
